sut:
  image: node:4
  command: sh -c 'npm install && npm test'
  volumes:
    - .:/app
  environment:
    - CI=true
  links:
    - vdinar-rpc
    - vdinar-rpc-ssl
    - vdinar-rpc-username-only
  working_dir: /app

vdinar-rpc:
  image: AndreaDejanGrande/vdinar-rpc
  command:
    -printtoconsole
    -rpcallowip=10.211.0.0/16
    -rpcallowip=172.17.0.0/16
    -rpcallowip=192.168.0.0/16
    -rpcpassword=bar
    -rpcport=19443
    -rpcuser=foo
    -server
  ports:
    - 19443:19443

vdinar-rpc-ssl:
  image: AndreaDejanGrande/vdinar-rpc
  command:
    -printtoconsole
    -rpcallowip=10.211.0.0/16
    -rpcallowip=172.17.0.0/16
    -rpcallowip=192.168.0.0/16
    -rpcpassword=bar
    -rpcport=19453
    -rpcssl
    -rpcsslcertificatechainfile=/etc/ssl/vdinard/cert.pem
    -rpcsslprivatekeyfile=/etc/ssl/vdinard/key.pem
    -rpcuser=foo
    -server
  volumes:
    - ./test/config/ssl:/etc/ssl/vdinard
  ports:
    - 19453:19453

vdinar-rpc-username-only:
  image: AndreaDejanGrande/vdinar-rpc
  command:
    -printtoconsole
    -rpcallowip=10.211.0.0/16
    -rpcallowip=172.17.0.0/16
    -rpcallowip=192.168.0.0/16
    -rpcport=19463
    -rpcuser=foo
    -server
  ports:
    - 19463:19463
